// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: true,
  // apiUrl: "http://localhost:3000/api",
  apiUrl: "https://financeiro.paglinque.com.br/api",
};
