// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: false,
  apiUrl: "http://localhost:3000/api",
};
