-- AlterTable
ALTER TABLE "despesas" ALTER COLUMN "data" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "data_pago" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "receitas" ALTER COLUMN "data" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "data_recebido" SET DATA TYPE TIMESTAMPTZ;
